### ISSUE TITLE
Class organization question with AIMA Ch. 3

### ISSUE THREAD

**Issue by burbon000** [udacity/aind-waffle-issues#1]
Do you know if there is a reason why we weren't given chapter 3 from AIMA to read when we were working on Isolation? I think it would have been immensely helpful given that it talks about searches and heuristics. I feel like we would have been so much better informed when trying to come up with our own heuristics and would have learned more.

**Comment by cgearhart** [comment]
Chapter 3 in AIMA deals with classical search, which doesn't apply directly to adversarial environments. The domains use different kinds of heuristics. This chapter is referenced in the learning plans for the classical search lessons.
