### ISSUE TITLE
Lesson 2 element 3 missing constraint

### ISSUE THREAD

**Issue by actuallymentor** [udacity/aind-waffle-issues#14]
In the N-queens text the constraint is "Constraints: No pair of queens can be on the same row or diagonal"
which should be "Constraints: No pair of queens can be on the same row, COLUMN or diagonal"

**Comment by cgearhart** [comment]
That constraint is enforced automatically by the choice of variables. For an NxN board, each of the N variables can represent a single column, and the question becomes "which row in each column should the queens be placed in".
