### ISSUE TITLE
CSP exercise z3 not found

### ISSUE THREAD

**Issue by juankikushima** [udacity/aind-waffle-issues#2]
I was going through the CSP exercise on the Jupiter Workspace and it seems the z3 module can't be found

**Comment by juankikushima** [comment]
![Screenshot (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6a5bebd08fbc0011e1a804/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0cb9d665043761260ea62864c7b96aea437a570a5b49a5495a5747f9f9892ba7e23b22d80d0be4c3714d36976345f3e5db55ea43a82a994d85bcbd8f4ec4e83b26e38c884c381b1755.png)

**Comment by cgearhart** [comment]
I have submitted a ticket to have the library added to the Workspaces environment, which may take a few days.

In the meantime, I've updated the notebook with static reference to the z3 binary, so you should be able to run "Reset Data" in the menu at the bottom left corner of the workspace and then it should work.

Note that the changes are NOT automatically propagated into the solution branch for the exercise, so if you switch you'll have to copy over the first two notebook cells to get the solution notebook to run properly.

**Comment by juankikushima** [comment]
Thanks a lot Chris!

Juan Kikushima
