### ISSUE TITLE
AI-ND, Lesson-1 Chapter 5

### ISSUE THREAD

**Issue by ranjitsisa** [udacity/aind-waffle-issues#20]
Dead link in google calendar hyperlink "AIND"
in the text below in AI-ND, Lesson-1 Chapter 5.

Office hours will be held by instructors, content creators and other Udacity staff to answer questions about the content and projects. You can find the regular schedule on this Google Calendar: AIND.

**Comment by cgearhart** [comment]
Updated. Thanks!
