### ISSUE TITLE
Projec 4 HTML NameError

### ISSUE THREAD

**Issue by seungjaeryanlee** [udacity/aind-waffle-issues#21]
Python/Jupyter doesn't seem to recognize HTML?

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-b9b433c78439> in <module>()
     30 assert len(emission_counts) == 12,        "Uh oh. There should be 12 tags in your dictionary."
     31 assert max(emission_counts["NOUN"], key=emission_counts["NOUN"].get) == 'time',        "Hmmm...'time' is expected to be the most common NOUN."
---> 32 HTML('<div class="alert alert-block alert-success">Your emission counts look good!</div>')

NameError: name 'HTML' is not defined

**Comment by cgearhart** [comment]
Added missing import to first notebook cell. Thanks for reporting!
