### ISSUE TITLE
Bug in error logger

### ISSUE THREAD

**Issue by WillieMaddox** [udacity/aind-waffle-issues#25]
In __init__.py under the isolation folder, the ERR_INFO format string does not match up with the arguments.  One solution would be to rearrange the args, so,

err, agents[0], agents[1], initial_state, game_state, game_history

would become,

err, initial_state, agents[0], agents[1], game_state, game_history

Either that, or swap the order in the ERR_INFO string at the top of the file.

**Comment by cgearhart** [comment]
Fixed in commit #d3520c8
