### ISSUE TITLE
z3-solver installation failure on Windows 7

### ISSUE THREAD

**Issue by pgstarkey** [udacity/aind-waffle-issues#3]
Installing/building z3-solver on Windows 7 fails as follows:

...
  To build Z3, open a [Visual Studio x64 Command Prompt], then
  type 'cd C:\Users\Paul\AppData\Local\Temp\pip-build-12gonoqd\z3-solver\core\bu
ild && nmake'

  Remark: to open a Visual Studio Command Prompt, go to: "Start > All Programs >
 Visual Studio > Visual Studio Tools"
  Building Z3
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for z3-solver
...

Do the remarks indicate that some C++ redistributables need to be installed?

The error messages above came from the conda installation process.  I then tried a pip install as recommended but got exactly the same error.

**Comment by cgearhart** [comment]
It looks like your system doesn't have a Visual Studio compiler installed: https://www.visualstudio.com/downloads/

Note that Z3 also has instructions for installing their pre-compiled binaries. https://github.com/Z3Prover/z3/wiki/Using-Z3Py-on-Windows

If you aren't able to get it working on your own machine, try the classroom workspace (use the Reset Data button in the menu at the bottom left corner to check for updates).
