### ISSUE TITLE
Make description of "Naked Twins strategy" more visible

### ISSUE THREAD

**Issue by seungjaeryanlee** [udacity/aind-waffle-issues#4]
Currently it's quite difficult to find info about Naked Twins strategy in the Udacity classroom. (No results appear when I use the searchbar) Either copying the definition from Peter Norvig's blog post mentioned in Part 1 Lesson 3-1 (Intro) or clarifying that the post contains the definition of Naked Twins strategy would be helpful.

**Comment by cgearhart** [comment]
Wow...sorry about that oversight. I've updated the git repo & workspace so that both the README file and function docstring include the definition of the naked twins strategy.
