### ISSUE TITLE
Calendar link is 404

### ISSUE THREAD

**Issue by actuallymentor** [udacity/aind-waffle-issues#8]
The office hours link redirects me here, which is a 404: https://classroom.udacity.com/nanodegrees/nd898/parts/75fe3a30-2531-4040-81e8-c4db62f32c0b/modules/2d1f0742-d727-4993-844b-2a390f9280a7/lessons/31f71698-b09c-44cd-a206-60836cca0e00/concepts/goo.gl/42FfMK

**Comment by cgearhart** [comment]
Looks like the classroom interpreted the link as a relative URL (the goo.gl/... part would work by itself). I've added a direct link to the calendar in its place.
